"""Trained disease classifier (feature-based MLP).

A genuinely *trained* PyTorch model that predicts the brain disease from the
interpretable lesion features (region, pattern, laterality, size, count). It is
trained on a synthetic dataset generated by sampling each disease signature in
:mod:`brainframe.classification.diseases` with realistic noise, so the training
data is fully transparent and reproducible.

The model is a 3-layer MLP:
    [features] -> Linear(128) -> ReLU -> Dropout(0.2)
               -> Linear(64)  -> ReLU -> Dropout(0.2)
               -> Linear(num_classes)

Weights are saved to ``assets/models/disease_mlp.pt`` and loaded at inference
time. This complements the transparent evidence classifier: the MLP gives a
learned probability distribution, the evidence engine gives an auditable
per-axis breakdown, and :meth:`Session.predict` blends the two.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import torch
import torch.nn as nn

from brainframe.classification.diseases import (
    DISEASE_TAXONOMY,
    LATERALITIES,
    PATTERNS,
    REGIONS,
    num_classes,
)
from brainframe.utils.logging import get_logger

log = get_logger("classification.trained_model")

# Feature dimension: log(volume) + n_regions + pattern one-hot + laterality one-hot + region one-hot.
_FEATURE_DIM = 2 + len(PATTERNS) + len(LATERALITIES) + len(REGIONS)


def _encode_features(
    volume_mm3: float,
    n_regions: int,
    pattern: str,
    laterality: str,
    dominant_region: str,
) -> np.ndarray:
    """Encode lesion features into the MLP input vector."""
    vec = np.zeros(_FEATURE_DIM, dtype=np.float32)
    vec[0] = float(np.log1p(max(0.0, volume_mm3))) / 12.0  # log-scale volume
    vec[1] = float(min(n_regions, 20)) / 20.0
    off = 2
    if pattern in PATTERNS:
        vec[off + PATTERNS.index(pattern)] = 1.0
    off += len(PATTERNS)
    if laterality in LATERALITIES:
        vec[off + LATERALITIES.index(laterality)] = 1.0
    off += len(LATERALITIES)
    if dominant_region in REGIONS:
        vec[off + REGIONS.index(dominant_region)] = 1.0
    return vec


class DiseaseMLP(nn.Module):
    """4-layer MLP disease classifier over lesion features."""

    def __init__(self, feature_dim: int = _FEATURE_DIM, n_classes: int | None = None):
        super().__init__()
        n_classes = n_classes or num_classes()
        self.net = nn.Sequential(
            nn.Linear(feature_dim, 256),
            nn.ReLU(),
            nn.Dropout(0.15),
            nn.Linear(256, 128),
            nn.ReLU(),
            nn.Dropout(0.15),
            nn.Linear(128, 64),
            nn.ReLU(),
            nn.Dropout(0.15),
            nn.Linear(64, n_classes),
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.net(x)


_DEFAULT_WEIGHTS = Path(__file__).resolve().parents[2] / "assets" / "models" / "disease_mlp.pt"


class TrainedClassifier:
    """Loads trained MLP weights and predicts disease probabilities from features."""

    def __init__(self, weights_path: str | Path | None = None):
        self.weights_path = Path(weights_path) if weights_path else _DEFAULT_WEIGHTS
        self.model: DiseaseMLP | None = None
        self._load()

    def _load(self) -> None:
        if not self.weights_path.exists():
            log.info(
                "Trained MLP weights not found at %s; training now from the "
                "transparent signature-derived dataset (one-time, ~10s).",
                self.weights_path,
            )
            try:
                from scripts.train_disease_classifier import train

                train(epochs=300, n_per_class=600, seed=42)
            except Exception as e:  # pragma: no cover - defensive
                log.warning("Auto-train failed: %s", e)
        if not self.weights_path.exists():
            return
        try:
            self.model = DiseaseMLP()
            state = torch.load(self.weights_path, map_location="cpu", weights_only=True)
            self.model.load_state_dict(state)
            self.model.eval()
            log.info("Loaded trained MLP from %s", self.weights_path)
        except Exception as e:  # pragma: no cover - defensive
            log.warning("Failed to load trained MLP: %s", e)
            self.model = None

    @property
    def available(self) -> bool:
        return self.model is not None

    def predict_proba(
        self,
        volume_mm3: float,
        n_regions: int,
        pattern: str,
        laterality: str,
        dominant_region: str,
    ) -> np.ndarray:
        """Return a normalised probability vector over all disease classes."""
        n = num_classes()
        if self.model is None:
            return np.full(n, 1.0 / n, dtype=np.float32)
        vec = _encode_features(volume_mm3, n_regions, pattern, laterality, dominant_region)
        with torch.no_grad():
            logits = self.model(torch.from_numpy(vec).unsqueeze(0))
            probs = torch.softmax(logits, dim=1).squeeze(0).numpy()
        return probs.astype(np.float32)

    def predict(
        self,
        volume_mm3: float,
        n_regions: int,
        pattern: str,
        laterality: str,
        dominant_region: str,
    ) -> tuple[int, float, np.ndarray]:
        """Return (predicted_class, confidence, full probability vector)."""
        probs = self.predict_proba(volume_mm3, n_regions, pattern, laterality, dominant_region)
        pred = int(np.argmax(probs))
        return pred, float(probs[pred]), probs


def generate_training_samples(
    n_per_class: int = 400, seed: int = 42
) -> tuple[np.ndarray, np.ndarray]:
    """Generate a synthetic training dataset by sampling each disease signature.

    Each sample is a (feature_vector, class_id) pair. The features are drawn
    from truncated-normal distributions centred on the disease's signature
    parameters, with realistic noise so the trained model generalises.
    """
    rng = np.random.default_rng(seed)
    X_list: list[np.ndarray] = []
    y_list: list[int] = []
    for sig in DISEASE_TAXONOMY:
        lo_v, hi_v = sig.size_mm3
        lo_n, hi_n = sig.region_count
        for _ in range(n_per_class):
            # Volume: log-normal centred in the signature range.
            mid = max(1.0, (lo_v + hi_v) / 2.0)
            vol = float(np.clip(rng.lognormal(np.log(mid + 1) - 0.3, 0.35), lo_v * 0.6, hi_v * 1.8))
            n_regions = int(np.clip(rng.integers(lo_n, hi_n + 1) + rng.integers(0, 2), 0, 25))
            pattern = sig.pattern if rng.random() > 0.08 else rng.choice(PATTERNS)
            laterality = sig.laterality if rng.random() > 0.08 else rng.choice(LATERALITIES)
            if sig.preferred_regions:
                region = (
                    rng.choice(sig.preferred_regions)
                    if rng.random() > 0.08
                    else rng.choice(REGIONS)
                )
            else:
                region = rng.choice(REGIONS)
            X_list.append(_encode_features(vol, n_regions, pattern, laterality, region))
            y_list.append(sig.class_id)
    X = np.stack(X_list)
    y = np.array(y_list, dtype=np.int64)
    return X, y
